import { DowryCategoryDetail } from "@/types/dowry";

export const dowryCategoryDetails: DowryCategoryDetail[] = [
  {
    id: "living-room",
    title: "Oturma Odası",
    icon: "sofa-outline",
    imageKey: "living-room",
    items: [
      { id: "koltuk-takimi", title: "Koltuk Takımı", completed: true },
      { id: "orta-sehpa", title: "Orta Sehpa", completed: true },
      { id: "tv-unitesi", title: "TV Ünitesi", completed: false },
      { id: "hali", title: "Halı", completed: true },
      { id: "fon-perde", title: "Fon Perde", completed: false },
      { id: "tul-perde", title: "Tül Perde", completed: false },
      { id: "zigon-sehpa", title: "Zigon Sehpa", completed: true },
      { id: "kitaplik", title: "Kitaplık", completed: false },
      { id: "lambader", title: "Lambader", completed: true },
      { id: "berjer", title: "Berjer", completed: false },
      { id: "dekoratif-ayna", title: "Dekoratif Ayna", completed: true },
      { id: "dresuar", title: "Dresuar", completed: false },
      { id: "yan-sehpa", title: "Yan Sehpa", completed: false },
      { id: "duvar-saati", title: "Duvar Saati", completed: true },
      { id: "televizyon", title: "Televizyon", completed: false },
      {
        id: "televizyon-unitesi-aksesuarlari",
        title: "Televizyon Ünitesi Aksesuarları",
        completed: true,
      },
      {
        id: "dekoratif-yastiklar",
        title: "Dekoratif Yastıklar",
        completed: false,
      },
      { id: "mumluk-seti", title: "Mumluk Seti", completed: true },
      { id: "vazo", title: "Vazo", completed: false },
      { id: "kırlent", title: "Kırlent", completed: true },
      { id: "sehpa-ortusu", title: "Sehpa Örtüsü", completed: false },
      { id: "salon-avize", title: "Salon Avize", completed: true },
      { id: "tablo", title: "Tablo", completed: false },
      { id: "dekoratif-tepsi", title: "Dekoratif Tepsi", completed: true },
      { id: "oda-kokusu", title: "Oda Kokusu", completed: false },
      { id: "perde-aksesuari", title: "Perde Aksesuarı", completed: false },
      { id: "tv-battaniyesi", title: "TV Battaniyesi", completed: true },
      { id: "dekoratif-obje", title: "Dekoratif Obje", completed: false },
      { id: "abajur", title: "Abajur", completed: true },
      { id: "salon-cicegi", title: "Salon Çiçeği", completed: false },
    ],
  },
  {
    id: "bedroom",
    title: "Yatak Odası",
    icon: "bed-king-outline",
    imageKey: "bedroom",
    items: [
      {
        id: "yatak-odasi-takimi",
        title: "Yatak Odası Takımı",
        completed: true,
      },
      { id: "yatak", title: "Yatak", completed: true },
      { id: "yorgan", title: "Yorgan", completed: false },
      { id: "nevresim-takimi", title: "Nevresim Takımı", completed: true },
      { id: "yastik", title: "Yastık", completed: false },
      { id: "pike-takimi", title: "Pike Takımı", completed: false },
      { id: "battaniye", title: "Battaniye", completed: true },
      { id: "hali", title: "Halı", completed: false },
      { id: "perde", title: "Perde", completed: true },
      { id: "komodin-lambasi", title: "Komodin Lambası", completed: false },
    ],
  },
  {
    id: "kitchen",
    title: "Mutfak",
    icon: "silverware-fork-knife",
    imageKey: "kitchen",
    items: [
      { id: "yemek-takimi", title: "Yemek Takımı", completed: true },
      { id: "kahvalti-takimi", title: "Kahvaltı Takımı", completed: true },
      { id: "tencere-seti", title: "Tencere Seti", completed: false },
      {
        id: "catal-kasik-bicak",
        title: "Çatal Kaşık Bıçak Seti",
        completed: true,
      },
      { id: "bardak-seti", title: "Bardak Seti", completed: false },
      { id: "saklama-kaplari", title: "Saklama Kapları", completed: false },
      { id: "baharatlik", title: "Baharatlık", completed: true },
      { id: "servis-tabagi", title: "Servis Tabağı", completed: false },
    ],
  },
  {
    id: "bathroom",
    title: "Banyo",
    icon: "shower-head",
    imageKey: "bathroom",
    items: [
      { id: "havlu-seti", title: "Havlu Seti", completed: true },
      { id: "bornoz-seti", title: "Bornoz Seti", completed: false },
      { id: "banyo-paspasi", title: "Banyo Paspası", completed: true },
      { id: "cop-kovasi", title: "Çöp Kovası", completed: false },
      { id: "sabunluk", title: "Sabunluk", completed: true },
      { id: "dis-fircalik", title: "Diş Fırçalık", completed: false },
    ],
  },
  {
    id: "home-decoration",
    title: "Ev Dekorasyon",
    icon: "flower-outline",
    imageKey: "home-decoration",
    items: [
      { id: "dekoratif-ayna", title: "Dekoratif Ayna", completed: true },
      { id: "tablo-seti", title: "Tablo Seti", completed: false },
      { id: "vazo", title: "Vazo", completed: true },
      { id: "mumluk", title: "Mumluk", completed: false },
      { id: "runner", title: "Runner", completed: true },
    ],
  },
  {
    id: "technology",
    title: "Teknolojik Aletler",
    icon: "television-classic",
    imageKey: "technology",
    items: [
      { id: "televizyon", title: "Televizyon", completed: true },
      { id: "supurge", title: "Süpürge", completed: false },
      { id: "utu", title: "Ütü", completed: true },
      { id: "kahve-makinesi", title: "Kahve Makinesi", completed: false },
      { id: "airfryer", title: "Airfryer", completed: true },
    ],
  },
  {
    id: "other",
    title: "Diğer",
    icon: "plus-box-outline",
    imageKey: "other",
    items: [
      { id: "ek-urun-1", title: "Ek Ürün", completed: false },
      { id: "ek-urun-2", title: "Ek Ürün 2", completed: true },
    ],
  },
];

export function getDowryCategoryDetail(categoryId: string) {
  return dowryCategoryDetails.find((category) => category.id === categoryId);
}
